### ISSUE TITLE
Encoded slashes don't work unless I switch to builtin engine

### ISSUE THREAD

**Issue by jordan-thoms** [phusion/passenger-ruby-heroku-demo#17]
Hi

Trying to switch our application over after having some issues with Puma - ran into an issue though, requests with slashes encoded in them (e.g. /documents/akd%2Fd%2Fs ) get mangled by nginx - it converts the encoded slashes into actual slashes, which means that Rails gives a 404 since it can't find something matching that route.

If i use the --engine builtin option, I don't have this issue - but I saw in another issue that you don't recommend that configuration on Heroku?

Thanks
Jordan

**Comment by FooBarWidget** [comment]
This mangling is handled by Nginx. There is no way to undo it. So unfortunately the only answer I can give you is: don't use encoded slashes.

The builtin engine doesn't mangle the URI, but we don't recommend it because it does not support gzip compression, and because it's less battle-tested than Nginx at handling public traffic. For example the builtin engine is not as aggressive as Nginx at handling timeouts and resource limits.
